name = "line-album-bot"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "line-media-storage"

[vars]
# 環境変数（実際の値は wrangler secret で設定）
# LINE_CHANNEL_SECRET = ""
# LINE_CHANNEL_ACCESS_TOKEN = ""